# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: defbb1cf9101ffa3a739a3b007cac4e6bafd2c2827f52525b6bc2d35f0b0e9ac7c90c377288624220b3b8a5fd93a0ea480546aaaefe0e7b02cc0aca4e23109c8

test:
  secret_key_base: 10cf257106c6188629e5b480945d81314b9f101061325cb2e0cd5753c9571359877130b496322a172f93262c4660f7124ed70bd918afe164e930a2ef783e21c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
